### ISSUE TITLE
Couldn't this project be greatly simplified?

### ISSUE THREAD

**Issue by JesseAldridge** [edebill/modulecounts#36]
Could you just have a list of trackers and a script that loops through them all?  Seems like this would be a lot easier for people to understand and contribute to.

Here's a proof of concept:

https://github.com/JesseAldridge/module-counter/

**Comment by edebill** [comment]
That is much simpler, but you lose the advantages of the database (backups, more flexible data querying, multiple server support, protection against data corruption), ability to deploy to heroku, and several edge cases that will complicate things once you add them (e.g. different link vs data urls, offsets because counts come back slightly wrong, need to include special headers with some requests).

In general, I happen to like working with rails - I prefer a big heavy framework that has lots of things available if I want them, rather than rolling my own. Yours is a valid approach, just not the one I'd choose.
